version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - PORT=${PORT}
    container_name: restaurant-api
    restart: always
    depends_on:
      - db

  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: restaurant-db
    volumes:
      - ./postgres:/var/lib/postgresql/data